USE [master]
GO
/****** Object:  Database [TestAPI]    Script Date: 11/14/2019 9:50:25 PM ******/
CREATE DATABASE [TestAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogSite', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\BlogSite.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BlogSite_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\BlogSite_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TestAPI] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestAPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TestAPI] SET  MULTI_USER 
GO
ALTER DATABASE [TestAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestAPI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [TestAPI]
GO
/****** Object:  User [blogsite]    Script Date: 11/14/2019 9:50:25 PM ******/
CREATE USER [blogsite] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [blogsite]
GO
/****** Object:  Table [dbo].[BlogComments]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogComments](
	[BlogCommentsId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [nvarchar](500) NOT NULL,
	[BlogId] [int] NOT NULL,
	[comment] [nvarchar](500) NULL,
	[datecreated] [datetime] NULL CONSTRAINT [DF_BlogsDetails_datecreated]  DEFAULT (getdate()),
 CONSTRAINT [PK_BlogsDetails] PRIMARY KEY CLUSTERED 
(
	[BlogCommentsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Blogs]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blogs](
	[BlogId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [nvarchar](500) NOT NULL,
	[title] [nvarchar](100) NULL,
	[Description] [nvarchar](1000) NULL,
	[datecreated] [datetime] NULL CONSTRAINT [DF_Table_1_datePosted]  DEFAULT (getdate()),
 CONSTRAINT [PK_Blogs] PRIMARY KEY CLUSTERED 
(
	[BlogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Ingredient](
	[uniqID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
	[amount] [int] NULL,
	[userName] [varbinary](50) NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[uniqID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Recipe]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipe](
	[UniqID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
	[description] [nvarchar](500) NULL,
	[imagePath] [nvarchar](500) NULL,
	[userName] [nvarchar](50) NULL,
 CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED 
(
	[UniqID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RecipeIngredient]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipeIngredient](
	[uniqID] [int] IDENTITY(1,1) NOT NULL,
	[recipeId] [int] NOT NULL,
	[ingredientId] [int] NOT NULL,
	[userName] [nvarchar](50) NULL,
 CONSTRAINT [PK_ReceipeIngredient] PRIMARY KEY CLUSTERED 
(
	[uniqID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 11/14/2019 9:50:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[PasswordHash] [varbinary](max) NULL,
	[PasswordSalt] [varbinary](max) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[BlogComments] ON 

INSERT [dbo].[BlogComments] ([BlogCommentsId], [userName], [BlogId], [comment], [datecreated]) VALUES (1, N'pshyani', 1, N'yes, it is great', CAST(N'2019-11-06 16:11:14.370' AS DateTime))
SET IDENTITY_INSERT [dbo].[BlogComments] OFF
SET IDENTITY_INSERT [dbo].[Blogs] ON 

INSERT [dbo].[Blogs] ([BlogId], [userName], [title], [Description], [datecreated]) VALUES (1, N'pshyani', N'ABC Kids', N'it is great', CAST(N'2019-11-06 16:10:51.173' AS DateTime))
SET IDENTITY_INSERT [dbo].[Blogs] OFF
SET IDENTITY_INSERT [dbo].[Users] ON 

INSERT [dbo].[Users] ([UserId], [UserName], [Email], [PasswordHash], [PasswordSalt]) VALUES (1, N'pshyani', N'pshyani@yahoo.com', 0x57BBAC1ACDFAC135B4226CB666265D155E019E46757F76695A28E29223E7175B9CF07469498002AA53B65A1020C009C2B7F739B67265B55228FFC1FF38996B1B, 0xD33EA21D21E1A46E9D26B226B109C39FA1A05A79742A37E8961225AA827E250A5DCED4BAC19C72A31B76FF30DC075705D432ADB651BA48372873E77982BACD428764CDA2B2ECB0411669D0EB1920872BBEDAC859A2B5F9A2AFEFF80ACFC19BE41A23DADB10DF31E00DE11A4C5C94171A2F7FC9D702285E9D8AF86B8C5A496CA1)
INSERT [dbo].[Users] ([UserId], [UserName], [Email], [PasswordHash], [PasswordSalt]) VALUES (2, N'ps', NULL, 0x485B39D36F14D3D317FB6A243656BA20EAF5EB2541C7F78169436CB186FD71B27F26FD65FBBD11284B93DD091F6D81A4144CDE7A8808BEAA96D2C13F289B08D6, 0xD62698C2719EAB525081D87F279BA2A7A05D789EDAA3D5FBFE16066E846DD8F9F3F39536AE80331602B7C0C328A536C5C403481CAD9A282A694BE42B63DD851A0D5BA90209EF85A5E0AB535DA7145FDEABAE007277661E26505D3E88E8C4B944BBD3CB2FE0EF319599008BFE4B1AF9859E08E397D9FA9C2737E21A20562599BE)
SET IDENTITY_INSERT [dbo].[Users] OFF
ALTER TABLE [dbo].[BlogComments]  WITH CHECK ADD  CONSTRAINT [FK_BlogComments_Blogs] FOREIGN KEY([BlogId])
REFERENCES [dbo].[Blogs] ([BlogId])
GO
ALTER TABLE [dbo].[BlogComments] CHECK CONSTRAINT [FK_BlogComments_Blogs]
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_ReceipeIngredient_Ingredient] FOREIGN KEY([ingredientId])
REFERENCES [dbo].[Ingredient] ([uniqID])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_ReceipeIngredient_Ingredient]
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_ReceipeIngredient_Recipe] FOREIGN KEY([recipeId])
REFERENCES [dbo].[Recipe] ([UniqID])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_ReceipeIngredient_Recipe]
GO
USE [master]
GO
ALTER DATABASE [TestAPI] SET  READ_WRITE 
GO

